DROP DATABASE sql10521425;
CREATE DATABASE IF NOT EXISTS sql10521425;
USE sql10521425;

-- Tabela Endereço --
CREATE TABLE IF NOT EXISTS ADDRESS (
    ID_ADDRESS BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ADDRESS_NUMBER VARCHAR(100) NOT NULL,
    COMPLEMENT VARCHAR(250),
    POSTAL_CODE VARCHAR(50) NOT NULL,
    DISTRICT VARCHAR(250) NOT NULL,
    CITY VARCHAR(250) NOT NULL,
    STATE VARCHAR(250) NOT NULL,
    COUNTRY VARCHAR(250) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- TABELA CLUB
CREATE TABLE IF NOT EXISTS CLUB (
	ID_CLUB  BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    CNPJ_NUMBER CHAR(14) NOT NULL,
    AVATAR VARCHAR(250),
    EMAIL VARCHAR(250) NOT NULL,
    PHONE VARCHAR (50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_ADDRESS BIGINT,
    CONSTRAINT FK_CLUB_ADDRESS FOREIGN KEY (ID_ADDRESS) REFERENCES ADDRESS(ID_ADDRESS)
);

-- TABELA USUARIO
CREATE TABLE IF NOT EXISTS USER (
	ID_USER BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    AVATAR VARCHAR(255),
    PHONE VARCHAR(50) NOT NULL,
    REGISTRY_NUMBER VARCHAR(50),
    ROLE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CLUB BIGINT NOT NULL,
    CONSTRAINT FK_USER_CLUB FOREIGN KEY (ID_CLUB) REFERENCES CLUB(ID_CLUB)
);

-- TABELA MODALIDADES
CREATE TABLE IF NOT EXISTS MODALITY (
	ID_MODALITY BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AREAS
CREATE TABLE IF NOT EXISTS AREA (
	ID_AREA BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CRETATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_MODALITY BIGINT NOT NULL,
    ID_CLUB BIGINT NOT NULL,
    CONSTRAINT FK_AREA_MODALITY FOREIGN KEY (ID_MODALITY) REFERENCES MODALITY(ID_MODALITY),
    CONSTRAINT FK_AREA_CLUB FOREIGN KEY (ID_CLUB) REFERENCES CLUB(ID_CLUB)
) ENGINE = innodb;

-- ATLETAS
CREATE TABLE IF NOT EXISTS ATHLETE (
	ID_ATHLETE BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    AVATAR VARCHAR(255),
    BIRTH_DATE DATE NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_ADDRESS BIGINT NOT NULL,
    ID_CLUB BIGINT NOT NULL,
    CONSTRAINT FK_ATHLETE_ADDRESS FOREIGN KEY (ID_ADDRESS) REFERENCES ADDRESS(ID_ADDRESS),
    CONSTRAINT FK_ATHLETE_CLUB FOREIGN KEY (ID_CLUB) REFERENCES CLUB(ID_CLUB)
);
-- AREA_ROLES
CREATE TABLE IF NOT EXISTS AREA_ROLE(
	ID_AREA_ROLE BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- AREA_USUARIO
CREATE TABLE IF NOT EXISTS USER_AREA (
	ID_USER_AREA BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_AREA BIGINT NOT NULL,
    ID_USER BIGINT NOT NULL,
    ID_AREA_ROLE BIGINT NOT NULL,
    CONSTRAINT FK_USER_AREA_AREA FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA),
    CONSTRAINT FK_USER_AREA_USER FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER),
    CONSTRAINT FK_USER_AREA_AREA_ROLE FOREIGN KEY (ID_AREA_ROLE) REFERENCES AREA_ROLE(ID_AREA_ROLE)
);
-- TREINAMENTO
CREATE TABLE IF NOT EXISTS TRAINING (
	ID_TRAINING BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    START_DATE DATETIME NOT  NULL,
    END_DATE DATETIME NOT NULL,
    NOTES TEXT,
    STATUS BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_AREA BIGINT NOT NULL,
    CONSTRAINT FK_TRAINING_AREA FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA)
);


-- TREINAMENTO ATLETA
CREATE TABLE IF NOT EXISTS TRAINING_ATHLETE(
	ID_TRAINING_ATHLETE BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOTE TEXT,
    STATUS BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_TRAINING BIGINT NOT NULL,
    ID_ATHLETE BIGINT NOT NULL,
    CONSTRAINT FK_TRAINING_ATHLETE_TRAINING FOREIGN KEY (ID_TRAINING) REFERENCES TRAINING(ID_TRAINING),
    CONSTRAINT FK_TRAINING_ATHLETE_ATHLETE FOREIGN KEY (ID_ATHLETE) REFERENCES ATHLETE(ID_ATHLETE)
);

-- AREA ATLETA
CREATE TABLE IF NOT EXISTS AREA_ATHLETE(
	ID_AREA_ATHLETE BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_AREA BIGINT NOT NULL,
    ID_ATHLETE BIGINT NOT NULL,
    CONSTRAINT FK_AREA_ATHLETE_AREA FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA),
    CONSTRAINT FK_AREA_ATHLETE_ATHLETE FOREIGN KEY (ID_ATHLETE) REFERENCES ATHLETE(ID_ATHLETE)
);

-- CATEGORIA
CREATE TABLE IF NOT EXISTS CATEGORY(
	ID_CATEGORY BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODALITY_CATEGORY (
	ID_MODALITY_CATEGORY BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_MODALITY BIGINT NOT NULL,
    ID_CATEGORY BIGINT NOT NULL,
    CONSTRAINT FK_MODALITY_CATEGORY_MODALITY FOREIGN KEY (ID_MODALITY) REFERENCES MODALITY(ID_MODALITY),
    CONSTRAINT FK_MODALITY_CATEGORY_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY)
);
