USE sql10521425;

-- ALter table
ALTER TABLE ADDRESS
	ADD COLUMN STREET VARCHAR(250) 
AFTER ID_ADDRESS;


UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 1;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 2;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 3;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 4;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 5;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 6;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 7;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 8;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 9;
UPDATE ADDRESS SET STREET = 'Av. Brasil' where ID_ADDRESS = 10;



SELECT * FROM ADDRESS;

