-- UPDATE NOMES DA TABELA DE TRAINING
update TRAINING SET NAME = "ALONGAMENTO" WHERE ID_TRAINING = 1;

SELECT * FROM TRAINING;

SET foreign_key_checks = 0; -- DESABILITA O CHECK DE FOREIGN KEY

-- EXCLUI TREINO REPETIDO
DELETE FROM TRAINING WHERE ID_TRAINING = 2;


-- LISTA A QUANTIDADE DE ATLETAS POR MODALIDADE E POR CLUBE
SELECT 
	CLUB.NAME AS 'NOME DO CLUB',
    MODALITY.NAME AS 'NOME DA MODALIDADE',
	COUNT(ATHLETE.NAME) as 'QUANTIDADE DE ATLETAS'
FROM 
	CLUB
INNER JOIN ATHLETE ON
	ATHLETE.ID_CLUB = CLUB.ID_CLUB
INNER JOIN AREA ON
	AREA.ID_CLUB = CLUB.ID_CLUB
INNER JOIN MODALITY ON
	MODALITY.ID_MODALITY = AREA.ID_MODALITY
group by CLUB.NAME, MODALITY.NAME;






	